### ISSUE TITLE
Why a length byte added when write message?

### ISSUE THREAD

**Issue by gaorongfu** [go-netty/go-netty-samples#1]
在客户端，通过netty.Channel的Write函数输出字节数组，接收端收到的数据却在最前端多出了一个字节
bhData := makeBeatHeartData()
	for {
		select {
		case <-bhtimer.C:
			log.Debug(LOG_TAG, "Upload beartheart data successfully:", bhData)
			outputChannel.Write(bhData)

比如下面两条数据是网络调试助手收到的数据，前面多了16和04，分别是两个字节数组的长度。请问这个字节是在哪个环节加上的？如何才能去掉这个字节？
[2021-06-17 20:40:40.316]# RECV HEX FROM  :50831>
16 AA 75 14 62 00 99 99 99 C7 42 CB 60 00 01 00 19 00 B2 00 B0 A6 F9 

[2021-06-17 20:41:39.331]# RECV HEX FROM  :50831>
04 AA 75 02 00

**Comment by limpo1989** [comment]
在编解码环节加上的，如果不想要加那么可以不注册编解码器

**Comment by gaorongfu** [comment]
嗯，后来查源代码发现了，在初始化lengthFieldCodec时使用了LengthFieldPrepender。注释掉这一行就会运行出空指针错误，所以我又写了一个没任何添加的CleanOutboundHandler。不知道更好的实现方式该怎么做，外部包貌似无法直接修改OutboundHandler成员。
return &lengthFieldCodec{
		byteOrder:           byteOrder,
		maxFrameLength:      maxFrameLength,
		lengthFieldOffset:   lengthFieldOffset,
		lengthFieldLength:   lengthFieldLength,
		lengthAdjustment:    lengthAdjustment,
		initialBytesToStrip: initialBytesToStrip,
		//OutboundHandler:     LengthFieldPrepender(byteOrder, lengthFieldLength, 0, false),
		OutboundHandler: &CleanOutboundHandler{},
	}

**Comment by limpo1989** [comment]
参考 https://github.com/go-netty/go-netty/issues/27 这个问题下面的方案

**Comment by gaorongfu** [comment]
好的，谢谢
