### ISSUE TITLE
不能发送大于1024 的数据

### ISSUE THREAD

**Issue by Neo110** [go-netty/go-netty-samples#3]
![1649657506(1)](https://user-images.githubusercontent.com/12504669/162675497-00d27a40-961c-4fd1-bd3c-118e876e1ea1.png)

**Comment by limpo1989** [comment]
```AddLast(frame.LengthFieldCodec(binary.LittleEndian, 1024, 0, 2, 0, 2))```

**Comment by limpo1989** [comment]
AddLast(frame.LengthFieldCodec(binary.LittleEndian, 1024, 0, 2, 0, 2))
在装配Pipeline的时候注意看下这里的 LengthFieldCodec 第二个参数 maxFrameLength
